services:
  - type: web
    name: a2sl-django
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn A2SL.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.8
